const quotes = [
    "I hoped to be skinny, by the end of this development",
    "listening to I'm gonna be(500 miles) by the proclaimers for inspiration",
    "can't believe I gamified walking to the store",
    "Get your spotify playlist ready",
    "If Mario can walk 100 000 steps you can walk to school",
    "Walking the length of one footbal field is around 200 steps. or something",
    "I was to busy coding this to go for a run",
    "I reccomend listening to nice music while walking, maybe Hoggormsafari",
    "If you weigh 90kg, you burn around 5 calories every minute when walking",
    "I hope I remember to delete this messsage",
    "Talk the talk, walk the walk, calk the calk",
    "At some point you will see all of these messages",
    "I have written over 100 messages, but due to statistics it will take you around an eternity to see them all",
    "have you seen this message before, or are you losing it?",
    "I'm very proud of you, but you don't know me so it's a bit creepy",
    "Imagine those calves, yum",
    "Walking improves mental health",
    "If you walk on average 9000 steps a day, in a lifetime that'll be the same as walking around the earth 3,5 times",
    "Good shoes lasts for around 800km, but don't push it.",
    "Walking can improve creatitivity. This app would have been better if I had walked 15k steps before building it",
    "People who track their steps take an average of 2500 steps more every day",
    "Walking is great excersise",
    "Working out is good for you, I know, quite a shocking one.",
    "If you walk 10 000 steps in crocs then you need to put them in sportmode",
    "These quotes would be better if I were funnier, too bad",
    "Remember to notice the scenary when you're going for your walk. Enjoy nature don't just exist in it.",
    "I love my family.",
    "Small things will give results given time, or so I've heard.",
    "This app was inspired by tiktok trends, don't tell them that",
    "One day this app might be really cool",
    "I named this app for Walkies because I miss my dog",
    "Life is not a competition, compete to be better than what you were, not what you hoped to be.",
    "These little quotes will not change your life, only you can do that.",
    "Some of these are qute sappy, put them on a sky background and post them to instagram with a nice caption",
    "Shits hard, but it gets better",
    "Being tired is good, life goes on, walk your steps",
    "Excuses will not give you results, unfortunately.",
    "Why does the word 'train' mean workout and locomotive?",
    "Trans rights are human rights",
    "Walk a mile in my shoes, but also take my phone so you can get some steps in for me",
    "If you want to lose weight, food is supposedly a good way to do it. I don't know I am fat.",
    "BRB makin sure that this app has already been made 50 times before",
    "Does this remind you of the Minecraft screen?",
    "I'm not gonna make you do anything, but you gambled and now you gotta pay your bills.",
    "Put it all on red, loose it all, start from the bottom, bet it all on black, loose it again, go for a walk",
    "One day this will be something really cool.",
    "I'd write some actual jokes, but I don't have the authority to do that.",
    "I googled quotes about walking, but they are genuinly just cringe. soz",
    "Pet your dog for me.",
    "Send me pictures of your dog, or other animal that's fine too.",
    "One day you'll have walked all over your town and know every spot. That's when you move, never surrender.",
    "This is what gambling gives you",
    "Thanks to my classmates at noroff for calling out my lazyness",
    "hugs and kisses, dreams and wishes... useless",
    "Why do tomorrow what you can do today?",
    "Saving the best for last",
    "Happy birthday, if it is your birthday"
]